//! One bounded observation request, charged durably before private TLS egress.
//! Transport success authenticates bytes, not causal completeness or solvency.
use crate::{
    Error,
    execution::{Gateway, Origin, ReadPermit, Reply},
    observation::{self, Kind, MAX_BODY, MAX_ROWS, Message},
};
use cinder_journal::{
    Backend, Committed, Journal, Protection,
    model::{CommitId, Transaction},
};
use serde::{Deserialize, Serialize};
use zeroize::Zeroizing;

/// Conservative unidentified-IP heavy-read cost, in tenths of a credit.
/// Pacifica's published range is 3–12 credits (rechecked 2026-10-06). This port
/// sends no PF-API-KEY and cannot assume a cheaper account/config-key tier.
pub const MIN_READ_COST: u32 = 120;

/// Trusted scheduler input; neither arbitrary URLs nor account overrides.
pub struct Poll {
    /// REST observations only; stream/disconnect kinds cannot become GETs.
    pub kind: Kind,
    /// Opaque cursor from previously committed observations, not a URL fragment.
    pub cursor: Option<String>,
    /// Unique durable credit reservation identity.
    pub reservation: CommitId,
    /// Unique response ingestion identity, distinct from the reservation.
    pub evidence: CommitId,
    /// Trusted injected request time in milliseconds.
    pub at: u64,
    /// Trusted cleanup scheduler only; public reads must leave this false.
    pub cleanup: bool,
}
impl std::fmt::Debug for Poll {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Poll([PRIVATE])")
    }
}

/// Non-clone single-delivery read capability, created after a journal reservation.
/// It is not a permission to run live tests or a terminal-history certificate.
pub struct Request {
    query: Query,
    permit: ReadPermit,
}
impl std::fmt::Debug for Request {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ReadRequest([PRIVATE])")
    }
}
impl Request {
    /// In-enclave transport consumes at its current trusted time immediately
    /// before sending once. An expired permit cannot expose a request.
    pub fn consume(self, now: u64) -> Result<Query, Error> {
        let (_, cost) = self.permit.consume(now)?;
        if cost < MIN_READ_COST {
            return Err(Error::Qualification);
        }
        Ok(self.query)
    }
}
/// Exact account-scoped GET target. Private routing metadata must not be logged
/// by the parent or transmitted outside the enclave-terminated TLS connection.
pub struct Query {
    origin: Origin,
    target: Zeroizing<String>,
}
impl std::fmt::Debug for Query {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ReadQuery([PRIVATE])")
    }
}
impl Query {
    /// Immutable bound native origin, not a response-selected destination.
    pub fn origin(&self) -> Origin {
        self.origin
    }
    /// Exact path and escaped query generated by the private scheduler.
    pub fn target(&self) -> &str {
        &self.target
    }
}

/// One-shot private transport; no retry, redirect, logging or invented response.
pub trait Transport {
    /// Consume the permit using trusted current time before opening a socket.
    fn get(&mut self, request: Request) -> Reply;
}

/// Delivery result, not permission to release reservations or initiate a payout.
pub enum Outcome {
    /// Exact response archived atomically with normalized events/diagnostic gaps.
    Ingested(Committed),
    /// HTTP 429 durably imposes the same pool-wide cooldown as signed actions.
    Limited,
    /// No usable response. Spent credits remain spent; there is no auto-retry.
    Unavailable,
}

fn target(kind: Kind, account: &str, cursor: Option<&str>) -> Result<Zeroizing<String>, Error> {
    let (path, paged) = match kind {
        Kind::Trades => ("/api/v1/trades/history", true),
        Kind::Funding => ("/api/v1/funding/history", true),
        Kind::Orders => ("/api/v1/orders/history", true),
        Kind::Positions => ("/api/v1/positions", false),
        Kind::Account => ("/api/v1/account", false),
        _ => return Err(Error::Qualification),
    };
    account_target(path, paged, account, cursor)
}
fn account_target(
    path: &str,
    paged: bool,
    account: &str,
    cursor: Option<&str>,
) -> Result<Zeroizing<String>, Error> {
    let decoded = bs58::decode(account)
        .into_vec()
        .map_err(|_| Error::Qualification)?;
    if decoded.len() != 32 || bs58::encode(decoded).into_string() != account {
        return Err(Error::Qualification);
    }
    let mut result = Zeroizing::new(format!("{path}?account={account}"));
    if paged {
        result.push_str(&format!("&limit={MAX_ROWS}"));
    } else if cursor.is_some() {
        return Err(Error::Qualification);
    }
    if let Some(cursor) = cursor {
        if cursor.is_empty()
            || cursor.len() > 256
            || !cursor.bytes().all(|b| (33..=126).contains(&b))
        {
            return Err(Error::Codec);
        }
        result.push_str("&cursor=");
        for byte in cursor.bytes() {
            if byte.is_ascii_alphanumeric() || b"-._~".contains(&byte) {
                result.push(char::from(byte));
            } else {
                result.push_str(&format!("%{byte:02X}"));
            }
        }
    }
    Ok(result)
}

/// Bounded account diagnostics for native funding qualification. These never
/// normalize cash, grant readiness, certify coverage or settle a funds operation.
#[derive(Clone, Copy, Serialize, Deserialize)]
pub enum Diagnostic {
    /// Documented account lending/margin settings.
    Settings,
    /// Documented borrowed balance and pending interest; missing is not zero.
    Loan,
    /// Documented balance effects; amounts/times alone do not identify a deposit.
    BalanceHistory,
    /// Retained legacy archive tag; fresh requests are unsupported.
    WithdrawalPending,
    /// Retained legacy archive tag; fresh requests are unsupported.
    WithdrawalHistory,
}
impl Diagnostic {
    fn route(self) -> Result<(&'static str, bool), Error> {
        Ok(match self {
            Self::Settings => ("/api/v1/account/settings", false),
            Self::Loan => ("/api/v1/account/loan", false),
            Self::BalanceHistory => ("/api/v1/account/balance/history", true),
            Self::WithdrawalPending | Self::WithdrawalHistory => return Err(Error::Qualification),
        })
    }
}
/// Trusted fixed-account diagnostic request, with separate durable identities.
pub struct DiagnosticPoll {
    /// Fixed endpoint selection, not caller-provided URLs.
    pub kind: Diagnostic,
    /// Spent credits persist before I/O.
    pub reservation: CommitId,
    /// Raw private evidence archive identity.
    pub evidence: CommitId,
    /// Trusted current clock time.
    pub at: u64,
    /// Reserved cleanup capacity, only for a trusted frozen-pool scheduler.
    pub cleanup: bool,
}
enum Selection {
    Observation { kind: Kind, cursor: Option<String> },
    Diagnostic(Diagnostic),
    Demo(crate::funding::demo::Metadata),
    Setup(crate::funding::setup::Metadata),
}
/// Non-clone completion identity created only after durable credit reservation.
/// It carries no signing key, journal mutation authority, or replacement request.
/// The one writer revalidates its exact retained reservation before ingestion.
pub struct Completion {
    contract: [u8; 32],
    reserved: Transaction,
    evidence: CommitId,
    selection: Selection,
}
struct Reservation {
    id: CommitId,
    evidence: CommitId,
    at: u64,
    cleanup: bool,
}
impl std::fmt::Debug for Completion {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ReadCompletion([PRIVATE])")
    }
}
fn reserve<B: Backend, P: Protection>(
    journal: &mut Journal<B, P>,
    gateway: &Gateway,
    input: Reservation,
    query: Query,
    selection: Selection,
    marker: Option<cinder_journal::model::PrivateBytes>,
) -> Result<(Request, Completion), Error> {
    let permit = gateway.reserve_read_with(journal, input.id, input.at, input.cleanup, marker)?;
    Ok((
        Request { query, permit },
        Completion {
            contract: gateway.release_commitment(journal.configuration())?,
            reserved: journal
                .transaction(input.id)
                .ok_or(Error::Qualification)?
                .clone(),
            evidence: input.evidence,
            selection,
        },
    ))
}
/// Reserve once under the mutation owner, then hand only this request to I/O.
/// Completion is a separate, single-use private token, not a freshness cache.
pub fn prepare_diagnostic<B: Backend, P: Protection>(
    journal: &mut Journal<B, P>,
    gateway: &Gateway,
    input: DiagnosticPoll,
) -> Result<(Request, Completion), Error> {
    let (profile, policy) = gateway.read_binding();
    if input.reservation == input.evidence
        || journal.transaction(input.evidence).is_some()
        || policy.read_cost < MIN_READ_COST
    {
        return Err(Error::Qualification);
    }
    let (path, paged) = input.kind.route()?;
    let query = Query {
        origin: policy.origin,
        target: account_target(path, paged, &profile.account, None)?,
    };
    let kind = input.kind;
    reserve(
        journal,
        gateway,
        Reservation {
            id: input.reservation,
            evidence: input.evidence,
            at: input.at,
            cleanup: input.cleanup,
        },
        query,
        Selection::Diagnostic(kind),
        None,
    )
}
/// Prepare one exact account/cursor request. No automatic paging or retries.
pub fn prepare_poll<B: Backend, P: Protection>(
    journal: &mut Journal<B, P>,
    gateway: &Gateway,
    input: Poll,
) -> Result<(Request, Completion), Error> {
    let (profile, policy) = gateway.read_binding();
    if input.reservation == input.evidence
        || journal.transaction(input.evidence).is_some()
        || policy.read_cost < MIN_READ_COST
    {
        return Err(Error::Qualification);
    }
    let query = Query {
        origin: policy.origin,
        target: target(input.kind, &profile.account, input.cursor.as_deref())?,
    };
    let view = observation::replay(journal, profile)?;
    if input.cursor.is_some() && view.cursors.get(&input.kind) != Some(&input.cursor) {
        return Err(Error::Qualification);
    }
    let selection = Selection::Observation {
        kind: input.kind,
        cursor: input.cursor,
    };
    reserve(
        journal,
        gateway,
        Reservation {
            id: input.reservation,
            evidence: input.evidence,
            at: input.at,
            cleanup: input.cleanup,
        },
        query,
        selection,
        None,
    )
}
/// Fixed-origin testnet GET prepared by the demo funding controller. The private
/// request marker and read spend are one durable transaction before I/O.
pub(crate) fn prepare_demo<B: Backend, P: Protection>(
    journal: &mut Journal<B, P>,
    gateway: &Gateway,
    metadata: crate::funding::demo::Metadata,
) -> Result<(Request, Completion), Error> {
    use crate::{execution::Origin, funding::demo};
    let (profile, policy) = gateway.read_binding();
    if policy.origin != Origin::Testnet
        || profile.environment != Origin::Testnet.url()
        || metadata.reservation == metadata.evidence
        || journal
            .transaction(cinder_journal::model::CommitId::new(metadata.evidence)?)
            .is_some()
        || policy.read_cost < MIN_READ_COST
    {
        return Err(Error::Qualification);
    }
    let mut target = account_target(
        metadata.endpoint.path(),
        true,
        &profile.account,
        metadata.cursor.as_deref(),
    )?;
    if metadata.endpoint == demo::Endpoint::Balance {
        target.push_str("&include_trades=true");
    }
    let marker = demo::marker(&metadata)?;
    reserve(
        journal,
        gateway,
        Reservation {
            id: cinder_journal::model::CommitId::new(metadata.reservation)?,
            evidence: cinder_journal::model::CommitId::new(metadata.evidence)?,
            at: metadata.at,
            cleanup: false,
        },
        Query {
            origin: policy.origin,
            target,
        },
        Selection::Demo(metadata),
        Some(marker),
    )
}
/// Fixed testnet setup reads. Raw bytes are retained as private evidence rather
/// than unresolved economic inputs or fabricated cash/reconciliation events.
pub(crate) fn prepare_setup<B: Backend, P: Protection>(
    journal: &mut Journal<B, P>,
    gateway: &Gateway,
    metadata: crate::funding::setup::Metadata,
) -> Result<(Request, Completion), Error> {
    let (profile, policy) = gateway.read_binding();
    if policy.origin != crate::execution::Origin::Testnet
        || profile.environment != policy.origin.url()
        || metadata.reservation == metadata.evidence
        || journal
            .transaction(CommitId::new(metadata.evidence)?)
            .is_some()
        || policy.read_cost < MIN_READ_COST
    {
        return Err(Error::Qualification);
    }
    let query = Query {
        origin: policy.origin,
        target: account_target(metadata.endpoint.path(), false, &profile.account, None)?,
    };
    let marker = crate::funding::setup::marker(&metadata)?;
    reserve(
        journal,
        gateway,
        Reservation {
            id: CommitId::new(metadata.reservation)?,
            evidence: CommitId::new(metadata.evidence)?,
            at: metadata.at,
            cleanup: false,
        },
        query,
        Selection::Setup(metadata),
        Some(marker),
    )
}
/// Rejoin the SAME authoritative writer after bounded I/O. Intervening commands
/// may advance the head; do not discard adverse native observations merely for
/// that change. Verify configuration and the original accepted reservation, then
/// commit at the current logical cut while preserving the actual receive time.
pub fn complete<B: Backend, P: Protection>(
    journal: &mut Journal<B, P>,
    gateway: &Gateway,
    completion: Completion,
    reply: Reply,
) -> Result<Outcome, Error> {
    let logical = journal.verified_state()?.logical_time();
    if completion.contract != gateway.release_commitment(journal.configuration())?
        || journal.transaction(completion.reserved.id) != Some(&completion.reserved)
        || journal.transaction(completion.evidence).is_some()
    {
        return Err(Error::Qualification);
    }
    let Reply::Response {
        status,
        body,
        received_at,
        retry_after_ms,
    } = reply
    else {
        return Ok(Outcome::Unavailable);
    };
    if received_at < completion.reserved.at {
        return Err(Error::Qualification);
    }
    if matches!(
        completion.selection,
        Selection::Diagnostic(_) | Selection::Demo(_) | Selection::Setup(_)
    ) && body.as_bytes().len() > MAX_BODY
    {
        return Err(Error::Qualification);
    }
    if status == 429 {
        gateway.record_read_limit(journal, completion.reserved.id, received_at, retry_after_ms)?;
        return Ok(Outcome::Limited);
    }
    let at = received_at.max(logical);
    let (profile, _) = gateway.read_binding();
    match completion.selection {
        Selection::Setup(metadata) => {
            let raw =
                crate::funding::setup::archive(&metadata, status, received_at, body.as_bytes())?;
            Ok(Outcome::Ingested(journal.commit(Transaction {
                id: completion.evidence,
                expected: journal.head(),
                at,
                evidence: vec![raw],
                inputs: vec![],
                order_observations: vec![],
                funds_observations: vec![],
                controls: vec![],
            })?))
        }
        Selection::Demo(metadata) => {
            let raw =
                crate::funding::demo::archive(&metadata, status, received_at, body.as_bytes())?;
            Ok(Outcome::Ingested(journal.commit(Transaction {
                id: completion.evidence,
                expected: journal.head(),
                at,
                evidence: vec![raw],
                inputs: vec![],
                order_observations: vec![],
                funds_observations: vec![],
                controls: vec![],
            })?))
        }
        Selection::Diagnostic(kind) => {
            use cinder_journal::model::{Input, PrivateBytes};
            let raw=PrivateBytes::new(serde_json::to_vec(&serde_json::json!({"schema":"cinder-native-diagnostic-v1","kind":kind,"account":profile.account,
                "status":status,"received_at":received_at,"body":body.as_bytes()})).map_err(|_|Error::Codec)?)?;
            Ok(Outcome::Ingested(journal.commit(Transaction {
                id: completion.evidence,
                expected: journal.head(),
                at,
                evidence: vec![],
                inputs: vec![Input {
                    source: profile.source,
                    source_cut: None,
                    authority_epoch: 0,
                    observed_at: received_at,
                    raw,
                    event: None,
                }],
                order_observations: vec![],
                funds_observations: vec![],
                controls: vec![],
            })?))
        }
        Selection::Observation { kind, cursor } => {
            if status != 200 {
                return Ok(Outcome::Unavailable);
            }
            if body.as_bytes().len() > MAX_BODY {
                return Err(Error::Limit);
            }
            let body = std::str::from_utf8(body.as_bytes())
                .map_err(|_| Error::Codec)?
                .to_owned();
            Ok(Outcome::Ingested(observation::ingest(
                journal,
                profile,
                Message {
                    kind,
                    account: profile.account.clone(),
                    cursor,
                    received_at,
                    body,
                },
                completion.evidence,
                at,
            )?))
        }
    }
}
/// Archive bounded non-429 responses, including missing accounts, without
/// economic effects. A 429 instead persists the existing shared cooldown record.
/// This is not a provider of Setup/Credit/Withdrawal/Coverage.
pub fn diagnostic<B: Backend, P: Protection, T: Transport>(
    journal: &mut Journal<B, P>,
    gateway: &Gateway,
    input: DiagnosticPoll,
    transport: &mut T,
) -> Result<Outcome, Error> {
    let (request, completion) = prepare_diagnostic(journal, gateway, input)?;
    complete(journal, gateway, completion, transport.get(request))
}

/// Poll one page through the same pool journal and credit policy as execution.
/// Only ordinary `ingest` is used: LI, terminal statuses, cursor exhaustion and
/// successful TLS do not fabricate a `Coverage` or source cut. A caller must
/// retain committed cursor progress; this function never auto-pages or retries.
pub fn poll<B: Backend, P: Protection, T: Transport>(
    journal: &mut Journal<B, P>,
    gateway: &Gateway,
    input: Poll,
    transport: &mut T,
) -> Result<Outcome, Error> {
    let (request, completion) = prepare_poll(journal, gateway, input)?;
    complete(journal, gateway, completion, transport.get(request))
}
