//! One bounded observation request, charged durably before private TLS egress.
//! Transport success authenticates bytes, not causal completeness or solvency.
use crate::{
    Error,
    execution::{Gateway, Origin, ReadPermit, Reply},
    observation::{self, Kind, MAX_BODY, MAX_ROWS, Message},
};
use cinder_journal::{Backend, Committed, Journal, Protection, model::CommitId};
use zeroize::Zeroizing;

/// Conservative unidentified-IP heavy-read cost, in tenths of a credit.
/// Pacifica's published range is 3–12 credits (rechecked 2026-10-06). This port
/// sends no PF-API-KEY and cannot assume a cheaper account/config-key tier.
pub const MIN_READ_COST: u32 = 120;

/// Trusted scheduler input; neither arbitrary URLs nor account overrides.
pub struct Poll {
    /// REST observations only; stream/disconnect kinds cannot become GETs.
    pub kind: Kind,
    /// Opaque cursor from previously committed observations, not a URL fragment.
    pub cursor: Option<String>,
    /// Unique durable credit reservation identity.
    pub reservation: CommitId,
    /// Unique response ingestion identity, distinct from the reservation.
    pub evidence: CommitId,
    /// Trusted injected request time in milliseconds.
    pub at: u64,
    /// Trusted cleanup scheduler only; public reads must leave this false.
    pub cleanup: bool,
}
impl std::fmt::Debug for Poll {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Poll([PRIVATE])")
    }
}

/// Non-clone single-delivery read capability, created after a journal reservation.
/// It is not a permission to run live tests or a terminal-history certificate.
pub struct Request {
    query: Query,
    permit: ReadPermit,
}
impl std::fmt::Debug for Request {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ReadRequest([PRIVATE])")
    }
}
impl Request {
    /// In-enclave transport consumes at its current trusted time immediately
    /// before sending once. An expired permit cannot expose a request.
    pub fn consume(self, now: u64) -> Result<Query, Error> {
        let (_, cost) = self.permit.consume(now)?;
        if cost < MIN_READ_COST {
            return Err(Error::Qualification);
        }
        Ok(self.query)
    }
}
/// Exact account-scoped GET target. Private routing metadata must not be logged
/// by the parent or transmitted outside the enclave-terminated TLS connection.
pub struct Query {
    origin: Origin,
    target: Zeroizing<String>,
}
impl std::fmt::Debug for Query {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ReadQuery([PRIVATE])")
    }
}
impl Query {
    /// Immutable bound native origin, not a response-selected destination.
    pub fn origin(&self) -> Origin {
        self.origin
    }
    /// Exact path and escaped query generated by the private scheduler.
    pub fn target(&self) -> &str {
        &self.target
    }
}

/// One-shot private transport; no retry, redirect, logging or invented response.
pub trait Transport {
    /// Consume the permit using trusted current time before opening a socket.
    fn get(&mut self, request: Request) -> Reply;
}

/// Delivery result, not permission to release reservations or initiate a payout.
pub enum Outcome {
    /// Exact response archived atomically with normalized events/diagnostic gaps.
    Ingested(Committed),
    /// HTTP 429 durably imposes the same pool-wide cooldown as signed actions.
    Limited,
    /// No usable response. Spent credits remain spent; there is no auto-retry.
    Unavailable,
}

fn target(kind: Kind, account: &str, cursor: Option<&str>) -> Result<Zeroizing<String>, Error> {
    let (path, paged) = match kind {
        Kind::Trades => ("/api/v1/trades/history", true),
        Kind::Funding => ("/api/v1/funding/history", true),
        Kind::Orders => ("/api/v1/orders/history", true),
        Kind::Positions => ("/api/v1/positions", false),
        Kind::Account => ("/api/v1/account", false),
        _ => return Err(Error::Qualification),
    };
    let decoded = bs58::decode(account)
        .into_vec()
        .map_err(|_| Error::Qualification)?;
    if decoded.len() != 32 || bs58::encode(decoded).into_string() != account {
        return Err(Error::Qualification);
    }
    let mut result = Zeroizing::new(format!("{path}?account={account}"));
    if paged {
        result.push_str(&format!("&limit={MAX_ROWS}"));
    } else if cursor.is_some() {
        return Err(Error::Qualification);
    }
    if let Some(cursor) = cursor {
        if cursor.is_empty()
            || cursor.len() > 256
            || !cursor.bytes().all(|b| (33..=126).contains(&b))
        {
            return Err(Error::Codec);
        }
        result.push_str("&cursor=");
        for byte in cursor.bytes() {
            if byte.is_ascii_alphanumeric() || b"-._~".contains(&byte) {
                result.push(char::from(byte));
            } else {
                result.push_str(&format!("%{byte:02X}"));
            }
        }
    }
    Ok(result)
}

/// Poll one page through the same pool journal and credit policy as execution.
/// Only ordinary `ingest` is used: LI, terminal statuses, cursor exhaustion and
/// successful TLS do not fabricate a `Coverage` or source cut. A caller must
/// retain committed cursor progress; this function never auto-pages or retries.
pub fn poll<B: Backend, P: Protection, T: Transport>(
    journal: &mut Journal<B, P>,
    gateway: &Gateway,
    input: Poll,
    transport: &mut T,
) -> Result<Outcome, Error> {
    let (profile, policy) = gateway.read_binding();
    if input.reservation == input.evidence
        || journal.transaction(input.evidence).is_some()
        || policy.read_cost < MIN_READ_COST
    {
        return Err(Error::Qualification);
    }
    let query = Query {
        origin: policy.origin,
        target: target(input.kind, &profile.account, input.cursor.as_deref())?,
    };
    // Reject skipped/repeated cursor scheduling before spending/exposure. The
    // parser separately validates the response's cursor and commits any gap.
    let view = observation::replay(journal, profile)?;
    if input.cursor.is_some() && view.cursors.get(&input.kind) != Some(&input.cursor) {
        return Err(Error::Qualification);
    }
    let permit = gateway.reserve_read(journal, input.reservation, input.at, input.cleanup)?;
    let reply = transport.get(Request { query, permit });
    let Reply::Response {
        status,
        body,
        received_at,
        retry_after_ms,
    } = reply
    else {
        return Ok(Outcome::Unavailable);
    };
    if received_at < input.at {
        return Err(Error::Qualification);
    }
    if status == 429 {
        gateway.record_read_limit(journal, input.reservation, received_at, retry_after_ms)?;
        return Ok(Outcome::Limited);
    }
    if status != 200 {
        return Ok(Outcome::Unavailable);
    }
    if body.as_bytes().len() > MAX_BODY {
        return Err(Error::Limit);
    }
    let body = std::str::from_utf8(body.as_bytes())
        .map_err(|_| Error::Codec)?
        .to_owned();
    let committed = observation::ingest(
        journal,
        profile,
        Message {
            kind: input.kind,
            account: profile.account.clone(),
            cursor: input.cursor,
            received_at,
            body,
        },
        input.evidence,
        received_at,
    )?;
    Ok(Outcome::Ingested(committed))
}
