#!/usr/bin/env node
// Offline only: create two fresh disposable identities, never use old wallets.
// Exact live approval remains a separately created, hash-bound private artifact.
import { mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { join } from 'node:path';
import { web3,ROUTE,ata } from './bindings.mjs';
import { LIMITS,STAGED_LIMITS,DELIVERY_LIMITS,privateRead,exclusive,validateManifest,sha } from './core.mjs';
import { checkEnvironment,configuredRpc,configuredWallet,validateSignerLocator,runDirectory,sources,tlsRoots } from './artifacts.mjs';
async function main() {
checkEnvironment();
const [directory,rpcFile,scenario]=process.argv.slice(2),reliable=['staged-reliable','staged-direct'].includes(scenario),
  staged=reliable||scenario==='staged-bootstrap';
if(!directory||!rpcFile||(scenario!==undefined&&!staged)||![4,5].includes(process.argv.length))throw Error('Usage: prepare.mjs RUN_DIRECTORY PRIVATE_RPC_FILE [staged-bootstrap|staged-reliable|staged-direct]');
const dir=runDirectory(directory,{exists:false}),rpc=configuredRpc(privateRead(rpcFile,4096)),u=new URL(rpc);
try { const {lstatSync}=await import('node:fs');lstatSync(dir);throw Error('Run namespace already exists'); }catch(e){if(e.code!=='ENOENT')throw e;}
if(u.origin!=='https://devnet.helius-rpc.com'||u.username||u.password||u.hash||u.pathname!=='/')throw Error('Fixed devnet RPC required');
const config=execFileSync('solana',['config','get'],{encoding:'utf8',env:{...process.env,NO_DNA:'1'}});
const wallet=configuredWallet(config);validateSignerLocator(wallet);
const sponsor=execFileSync('solana',['address'],{encoding:'utf8',env:{...process.env,NO_DNA:'1'}}).trim();
new web3.PublicKey(sponsor);
mkdirSync(dir,{mode:0o700,recursive:true});
const roles={};for(const role of ['owner','broker']) {
  const key=web3.Keypair.generate();roles[role]=key.publicKey.toBase58();
  exclusive(join(dir,`${role}.key`),JSON.stringify([...key.secretKey]));key.secretKey.fill(0);
}
const manifest={schema:reliable?'cinder-native-staged-delivery-v1':staged?'cinder-native-staged-bootstrap-v1':'cinder-native-qualification-v1',created:new Date().toISOString(),cluster:'devnet',aws:false,shipping:false,
  native_origin:'https://test-api.pacifica.fi',wss_origin:'wss://test-ws.pacifica.fi/ws',rpc_origin:u.origin,
  genesis:'EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG',owner:roles.owner,broker:roles.broker,sponsor,
  owner_tokens:ata(roles.owner).toBase58(),broker_tokens:ata(roles.broker).toBase58(),route:ROUTE,
  limits:reliable?DELIVERY_LIMITS:staged?STAGED_LIMITS:LIMITS,bootstrap_exception:!staged,lost_native_reply:!staged,...(staged?{test_capital_only:true}:{}),
  ...(reliable?{faucet_mode:scenario==='staged-direct'?'broker-direct':'owner-via-broker'}:{}),withdraw_uuid:randomUUID(),
  sponsor_transfers:{owner:'35000000',broker:'25000000'},sources:sources(),tls_roots:tlsRoots(),node:process.versions.node,
  rpc_config_hash:sha(rpc),sponsor_locator_hash:sha(wallet),source_bytecode_equivalence:false,
  scope_approval:staged?'User approved separately sealed staged faucet-only bootstrap: 20 USDP, 0.10 devnet SOL, no AWS/customer assets, on 2026-10-08':'User approved 20 faucet USDP, 0.10 devnet SOL, no AWS and bounded bootstrap on 2026-10-08',
  execution_approval:'pending'};
const seal=validateManifest(manifest);
exclusive(join(dir,'config.json'),{rpc,wallet});exclusive(join(dir,'manifest.json'),manifest);
exclusive(join(dir,'MAPPINGS.md'),`# Sealed native observation mappings\n\nCanonical Solana loader-v3: ${ROUTE.loader}. Require the pinned native program-data address, loader slot and upgrade authority; do not accept a changed deployment.\n\nUse Pacifica's documented account/balance/history for an explicit empty baseline page and later balance observations. A final page is not a complete causal frontier. Do not substitute spot history or assume undocumented perp withdrawal-history/pending endpoints exist.\n\nThe documented account_transfers envelope contains one event object. Decode and retain it before original signature/batch joins; unknown/malformed data cannot silently become an empty event list. Closeout uses the observed account pending_balance and does not assert all pending operations are complete.\n\nNo source cut, controller credit, native UUID recovery, financial completion, AWS qualification or shipping activation follows from these diagnostic mappings.\n`);
exclusive(join(dir,'REVIEW.md'),`# Exact native-semantics execution record\n\nSeal: ${seal}\n\nCluster: Solana devnet / Pacifica testnet. No AWS or program deployment.\n\n- Sponsor ${sponsor}: 0.035 SOL to owner ${roles.owner}, 0.025 SOL to broker ${roles.broker}. Total sponsor debit (including network fees) must remain below 0.10 SOL.\n- Faucet mints 20 USDP to the fresh owner; transfer exactly 20 to broker; one native deposit of 20; one original UUID withdrawal of 20; return the confirmed net USDP to owner. No other asset route.\n- The documented native withdrawal fee is 1 USDP. The 2-USDP ceiling is a receipt acceptance limit, NOT a signed maximum fee: the native API provides no max-fee field. An unexpected fee stops qualification and remains in the actual evidence.\n- Fee payers: sponsor for the two SOL funding transactions, owner for faucet/token allocation, broker for native deposit/net return. No priority fees; simulation and fee/remaining-balance checks precede signing/exposure.\n- Native program ${ROUTE.program}; mint ${ROUTE.mint} (6 decimals); venue vault ${ROUTE.vault}. Historical deployment slot/upgrade authority must revalidate. The initial executable digest is retained; subsequent sends require unchanged loader slot/authority. This does not prove source equivalence.\n- 20 minutes; 200 native HTTP / 400 RPC / eight finite WSS connections, including cleanup. No trading, agents, borrowing, subaccounts, recovery activation or shipping gate change.\n- Pre-deposit lending-disable check, approved 120-second deposit-first exception for the exact fresh-account rejection. Unknown settings outcomes stop rather than trigger another POST.\n- Original request/wire before exposure; callback-level loss withholds the withdrawal response from controller acceptance. Separate private audit evidence may contain the experiment, never fabricate controller recovery or a complete source cut. No automatic retries, live restart or replacement UUID/signature.\n- Public-code/lock/TLS digests are in manifest.json. Private keys, signed wires, RPC URL and raw traces remain local, mode 0600. JS keys have no secure-erasure guarantee. Unused devnet gas/token-account rent remains in the fresh test accounts; no unapproved account closure or rescue transfer.\n\nExact execution approval is pending. A separate approval.json bound to this seal and a <=24-hour expiry is required before any live request. Preflight rejects cluster/layout/deployment drift and displays/retains simulation evidence before submission; a failed prerequisite stops this invocation.\n`);
console.log(JSON.stringify({prepared:dir,seal,owner:roles.owner,broker:roles.broker,sponsor,faucet_mode:manifest.faucet_mode??'owner-via-broker',live:false}));
if(staged)exclusive(join(dir,'STAGED-REVIEW.md'),`# Separate staged test-capital bootstrap\n\nSeal: ${seal}\n\nThis manifest supersedes the legacy-scenario bullets in REVIEW.md **for this fresh invocation only**. No old identity, approval or 120-second exception is reused.\n\nDeposit exactly 20 faucet USDP once, using only test/house capital. Wait for positive idle account and zero-debt loan-cache observations (at most four account/loan pairs), then submit one original lending-disable request and read back settings/loan/account/positions/orders. Require the exact original deposit signature/full amount in native history and nonpending full balance corroboration. A separate five-minute staging deadline applies; the total invocation remains 20 minutes. Customer funding and trading remain disabled.\n\nOne original UUID withdrawal retains its ACK rather than injecting reply loss. Independently match the ACK batch, native instruction and finalized recipient token delta; return only confirmed net. Verify an empty disabled-lending, zero-debt/no-exposure baseline afterward. No economic resend, re-sign, automatic setting retry, customer credit, source cut, financial completion, recovery or shipping activation. Setup failure allows only the planned original withdrawal containment; uncertain withdrawal/deposit/payment stops. Amounts, recipients, fee payers, fee acceptance ceiling, source/TLS seal, cleanup reserves and all other limits are unchanged from REVIEW.md.\n\nApproval must separately bind this exact seal and explicitly name the staged scenario.\n`);
if(reliable)exclusive(join(dir,'DELIVERY-REVIEW.md'),`# Persistent testnet diagnostic variant\n\nSeal: ${seal}\n\nThe latest user explicitly authorized continued independent testnet transfers/checks until credit behavior is established, without another permission request after each failure. This variant supersedes the earlier staging timing/funding bullets for this new invocation only.\n\nOne original signed wire per action; RPC maxRetries=5 forwards the same signed transaction, never changes its signature or renews its blockhash. At most 60 original-status polls, 2-second cadence. Native initialization uses at most 12 account/loan pairs within ten minutes; total invocation remains 20 minutes and HTTP/RPC/WSS caps remain 200/400/8. HTTP remains one request per 12 seconds; 429 stops, no quota evasion.\n\nFunding mode: ${manifest.faucet_mode}. owner-via-broker mints 20 faucet USDP to the owner, allocates 20 to broker, then deposits. broker-direct mints 20 directly to broker, creates an empty owner return ATA, then deposits; this isolates the official direct funding/initialization path. Sponsor funds both identities as already documented, owner pays return-ATA creation, broker pays direct faucet/deposit. Only confirmed native net can be returned to the fixed owner.\n\nNo customer funds, trading, shipping gate, mainnet, AWS, existing-wallet venue action, economic resend or historical invocation restart. Independent rounds remain separate originals under the latest user authorization.\n`);
}
try { await main(); } catch {console.error('Offline preparation failed. Inspect the local configuration/permissions; no live request was made.');process.exitCode=1;}
