import { test } from 'node:test';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { serialFromEntropy } from './serial.mjs';
import { fixtures } from './fixtures.mjs';
import { verifyWithRoot } from './verifier.mjs';
import { certificateSerial, verifiedLeaf } from './certificates.mjs';
import { root as awsRoot } from './aws-root.mjs';
import capture from './aws-serial-padding-capture.json' with { type: 'json' };

test('certificate serial accepts only positive minimal magnitudes up to 20 bytes', () => {
  for (let n = 1; n <= 20; n++) {
    assert.equal(certificateSerial(new Uint8Array(n).fill(127)), true);
    assert.equal(certificateSerial(Uint8Array.of(0, ...new Uint8Array(n).fill(128))), true);
    assert.equal(certificateSerial(new Uint8Array(n).fill(128)), false);
    assert.equal(certificateSerial(Uint8Array.of(0, ...new Uint8Array(n).fill(127))), false);
  }
  for (const bad of [undefined, [], new Uint8Array(), Uint8Array.of(0),
    Uint8Array.of(0,0,128), new Uint8Array(21).fill(1),
    Uint8Array.of(0,...new Uint8Array(21).fill(128))]) {
    assert.equal(certificateSerial(bad), false);
  }
});

test('observed AWS sign-padded serial retains fixed-root path and expiry checks', async () => {
  const decode = b => Uint8Array.from(Buffer.from(b,'base64'));
  const path = { chain: capture.chain.map(decode), certificate: decode(capture.certificate) };
  await verifiedLeaf(path,awsRoot(),capture.capturedAt);
  await assert.rejects(() => verifiedLeaf(path,awsRoot(),capture.capturedAt + 86400000));
  const corrupted = path.certificate.slice(); corrupted[corrupted.length-1] ^= 1;
  await assert.rejects(() => verifiedLeaf({...path,certificate:corrupted},awsRoot(),capture.capturedAt));
});

test('fixture serials are positive, minimal and do not mutate entropy', () => {
  for (let leading = 0; leading < 16; leading++) {
    for (const top of [1, 127, 128, 255]) {
      const entropy = new Uint8Array(16).fill(1);
      entropy.fill(0, 0, leading); entropy[leading] = top;
      const original = entropy.slice(), encoded = serialFromEntropy(entropy);
      const magnitude = entropy.slice(leading);
      assert.deepEqual(encoded, top < 128 ? magnitude : Uint8Array.of(0, ...magnitude));
      assert.deepEqual(entropy, original);
      assert.ok(encoded.length <= 17 && !(encoded[0] & 128));
      assert.ok(encoded.length === 1 || encoded[0] !== 0 || encoded[1] & 128);
    }
  }
  assert.throws(() => serialFromEntropy(new Uint8Array(16)), /zero fixture serial/);
  for (const bad of [undefined, [], new Uint8Array(0), new Uint8Array(15), new Uint8Array(17)]) {
    assert.throws(() => serialFromEntropy(bad), /fixture serial entropy/);
  }
});

test('leading-zero and sign-padding certificate fixtures pass both independent verifiers', async () => {
  const original = crypto.getRandomValues;
  try {
    for (const top of [127, 128]) {
      // Exercise the real certificate generator deterministically. Crypto keys
      // are still generated by WebCrypto; only its JS serial request is replaced.
      crypto.getRandomValues = function(bytes) {
        if (bytes.length === 16) { bytes.fill(1); bytes[0] = 0; bytes[1] = top; return bytes; }
        return original.call(this, bytes);
      };
      const corpus = await fixtures(fileURLToPath(new URL('../../../', import.meta.url)));
      assert.equal(corpus.length, 40);
      for (const f of corpus.filter(f => f.expected)) {
        const context = Object.fromEntries(Object.entries(f.context)
          .map(([key, value]) => [key, Array.isArray(value) ? Uint8Array.from(value) : value]));
        await verifyWithRoot(Uint8Array.from(f.quote), Uint8Array.from(f.policy), context, Uint8Array.from(f.root));
      }
    }
  } finally { crypto.getRandomValues = original; }
});
