[toolchain]
anchor_version = "1.2.0"

[workspace]
members = ["cinder-vault"]

[programs.localnet]
cinder_vault = "FMu4FVg4kWABgsPg8Q5Q8Z3wieTtVgtG2gapCSdGT7RX"

[provider]
cluster = "Localnet"
wallet = "/dev/null"
